In [19]:
#Dependencies

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime

In [2]:
# Store file path.
file = ("Resources/data.gov.FEMADeclarations.10.16.17.xlsx")

xl = pd.ExcelFile("Resources/data.gov.FEMADeclarations.10.16.17.xlsx")

print(xl.sheet_names)

['Instructions', 'MetaData', 'FEMA Declarations']

In [3]:
fema_declarations = xl.parse("FEMA Declarations")
fema_declarations

,Disaster Number,IH Program Declared,IA Program Declared,PA Program Declared,HM Program Declared,State,Declaration Date,Disaster Type,Incident Type,Title,Incident Begin Date,Incident End Date,Disaster Close Out Date,Place Code,Declared County/Area
0,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99005.0,Allendale (County)
1,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99007.0,Anderson (County)
2,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99009.0,Bamberg (County)
3,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99011.0,Barnwell (County)
4,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99013.0,Beaufort (County)
5,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99015.0,Berkeley (County)
6,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99019.0,Charleston (County)
7,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99029.0,Colleton (County)
8,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99035.0,Dorchester (County)
9,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99037.0,Edgefield (County)
10,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99043.0,Georgetown (County)
11,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99049.0,Hampton (County)
12,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99053.0,Jasper (County)
13,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99065.0,McCormick (County)
14,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99073.0,Oconee (County)
15,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99077.0,Pickens (County)
16,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99001.0,Acadia (Parish)
17,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99003.0,Allen (Parish)
18,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99007.0,Assumption (Parish)
19,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99011.0,Beauregard (Parish)
20,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99019.0,Calcasieu (Parish)
21,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99023.0,Cameron (Parish)
22,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99031.0,De Soto (Parish)
23,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99045.0,Iberia (Parish)
24,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99053.0,Jefferson Davis (Parish)
25,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99055.0,Lafayette (Parish)
26,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99057.0,Lafourche (Parish)
27,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99069.0,Natchitoches (Parish)
28,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99075.0,Plaquemines (Parish)
29,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99079.0,Rapides (Parish)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47574,31,No,Yes,Yes,Yes,AK,1954-11-10 00:00:00,DR,Other,SEVERE HARDSHIP,1954-11-10 00:00:00,1954-11-10 00:00:00,1957-09-01,NaN,NaN
47575,30,No,Yes,Yes,Yes,IN,1954-10-26 00:00:00,DR,Flood,FLOOD,1954-10-26 00:00:00,1954-10-26 00:00:00,1956-03-01,NaN,NaN
47576,28,No,Yes,Yes,Yes,NC,1954-10-17 00:00:00,DR,Hurricane,HURRICANE,1954-10-17 00:00:00,1954-10-17 00:00:00,1959-01-01,NaN,NaN
47577,29,No,Yes,Yes,Yes,SC,1954-10-17 00:00:00,DR,Hurricane,HURRICANE,1954-10-17 00:00:00,1954-10-17 00:00:00,1959-01-01,NaN,NaN
47578,27,No,Yes,Yes,Yes,NM,1954-10-13 00:00:00,DR,Flood,FLOOD,1954-10-13 00:00:00,1954-10-13 00:00:00,1959-12-01,NaN,NaN
47579,26,No,Yes,Yes,Yes,NY,1954-10-07 00:00:00,DR,Hurricane,HURRICANES,1954-10-07 00:00:00,1954-10-07 00:00:00,1956-12-01,NaN,NaN
47580,25,No,Yes,Yes,Yes,CT,1954-09-17 00:00:00,DR,Hurricane,HURRICANES,1954-09-17 00:00:00,1954-09-17 00:00:00,1957-01-01,NaN,NaN
47581,24,No,Yes,Yes,Yes,ME,1954-09-13 00:00:00,DR,Hurricane,HURRICANES,1954-09-13 00:00:00,1954-09-13 00:00:00,1956-12-01,NaN,NaN
47582,22,No,Yes,Yes,Yes,MA,1954-09-02 00:00:00,DR,Hurricane,HURRICANES,1954-09-02 00:00:00,1954-09-02 00:00:00,1956-12-01,NaN,NaN
47583,23,No,Yes,Yes,Yes,RI,1954-09-02 00:00:00,DR,Hurricane,HURRICANES,1954-09-02 00:00:00,1954-09-02 00:00:00,1956-12-01,NaN,NaN
47584,21,No,Yes,Yes,Yes,WV,1954-08-04 00:00:00,DR,Flood,FLOOD,1954-08-04 00:00:00,1954-08-04 00:00:00,1957-05-01,NaN,NaN
47585,20,No,Yes,Yes,Yes,SD,1954-07-31 00:00:00,DR,Flood,FLOOD,1954-07-31 00:00:00,1954-07-31 00:00:00,1956-02-01,NaN,NaN
47586,19,No,Yes,Yes,Yes,NV,1954-07-14 00:00:00,DR,Earthquake,EARTHQUAKE,1954-07-14 00:00:00,1954-07-14 00:00:00,1957-08-01,NaN,NaN
47587,18,No,Yes,Yes,Yes,TX,1954-07-01 00:00:00,DR,Flood,FLOOD,1954-07-01 00:00:00,1954-07-01 00:00:00,1959-07-01,NaN,NaN
47588,17,No,Yes,Yes,Yes,IA,1954-06-23 00:00:00,DR,Flood,FLOOD,1954-06-23 00:00:00,1954-06-23 00:00:00,1956-02-01,NaN,NaN
47589,16,No,Yes,Yes,Yes,GA,1954-03-17 00:00:00,DR,Tornado,TORNADO,1954-03-17 00:00:00,1954-03-17 00:00:00,1956-11-01,NaN,NaN
47590,15,No,Yes,Yes,Yes,CA,1954-02-05 00:00:00,DR,Flood,FLOOD & EROSION,1954-02-05 00:00:00,1954-02-05 00:00:00,1957-09-01,NaN,NaN
47591,14,No,Yes,Yes,Yes,MS,1953-12-06 00:00:00,DR,Tornado,TORNADO,1953-12-06 00:00:00,1953-12-06 00:00:00,1956-06-01,NaN,NaN
47592,13,No,Yes,Yes,Yes,AK,1953-10-30 00:00:00,DR,Other,SEVERE HARDSHIP,1953-10-30 00:00:00,1953-10-30 00:00:00,1957-09-01,NaN,NaN
47593,12,No,Yes,Yes,Yes,FL,1953-10-22 00:00:00,DR,Flood,FLOOD,1953-10-22 00:00:00,1953-10-22 00:00:00,1956-05-01,NaN,NaN
47594,11,No,Yes,Yes,Yes,NH,1953-07-02 00:00:00,DR,Fire,FOREST FIRE,1953-07-02 00:00:00,1953-07-02 00:00:00,1956-02-01,NaN,NaN
47595,9,No,Yes,Yes,Yes,TX,1953-06-19 00:00:00,DR,Flood,FLOOD,1953-06-19 00:00:00,1953-06-19 00:00:00,1958-01-01,NaN,NaN
47596,7,No,Yes,Yes,Yes,MA,1953-06-11 00:00:00,DR,Tornado,TORNADO,1953-06-11 00:00:00,1953-06-11 00:00:00,1956-06-01,NaN,NaN
47597,8,No,Yes,Yes,Yes,IA,1953-06-11 00:00:00,DR,Flood,FLOOD,1953-06-11 00:00:00,1953-06-11 00:00:00,1955-11-01,NaN,NaN
47598,6,No,Yes,Yes,Yes,MI,1953-06-09 00:00:00,DR,Tornado,TORNADO,1953-06-09 00:00:00,1953-06-09 00:00:00,1956-03-30,NaN,NaN
47599,5,No,Yes,Yes,Yes,MT,1953-06-06 00:00:00,DR,Flood,FLOODS,1953-06-06 00:00:00,1953-06-06 00:00:00,1955-12-01,NaN,NaN
47600,4,No,Yes,Yes,Yes,MI,1953-06-02 00:00:00,DR,Tornado,TORNADO,1953-06-02 00:00:00,1953-06-02 00:00:00,1956-02-01,NaN,NaN
47601,3,No,Yes,Yes,Yes,LA,1953-05-29 00:00:00,DR,Flood,FLOOD,1953-05-29 00:00:00,1953-05-29 00:00:00,1960-02-01,NaN,NaN
47602,2,No,Yes,Yes,Yes,TX,1953-05-15 00:00:00,DR,Tornado,TORNADO & HEAVY RAINFALL,1953-05-15 00:00:00,1953-05-15 00:00:00,1958-01-01,NaN,NaN
47603,1,No,Yes,Yes,Yes,GA,1953-05-02 00:00:00,DR,Tornado,TORNADO,1953-05-02 00:00:00,1953-05-02 00:00:00,1954-06-01,NaN,NaN

In [21]:
fema_declarations['year'] = fema_declarations['Declaration Date'].dt.year
fema_declarations

,Disaster Number,IH Program Declared,IA Program Declared,PA Program Declared,HM Program Declared,State,Declaration Date,Disaster Type,Incident Type,Title,Incident Begin Date,Incident End Date,Disaster Close Out Date,Place Code,Declared County/Area,year
0,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99005.0,Allendale (County),2017
1,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99007.0,Anderson (County),2017
2,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99009.0,Bamberg (County),2017
3,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99011.0,Barnwell (County),2017
4,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99013.0,Beaufort (County),2017
5,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99015.0,Berkeley (County),2017
6,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99019.0,Charleston (County),2017
7,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99029.0,Colleton (County),2017
8,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99035.0,Dorchester (County),2017
9,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99037.0,Edgefield (County),2017
10,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99043.0,Georgetown (County),2017
11,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99049.0,Hampton (County),2017
12,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99053.0,Jasper (County),2017
13,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99065.0,McCormick (County),2017
14,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99073.0,Oconee (County),2017
15,4346,No,No,Yes,Yes,SC,2017-10-16 15:45:00,DR,Hurricane,HURRICANE IRMA,2017-09-06 00:00:00,2017-09-13 23:59:00,NaT,99077.0,Pickens (County),2017
16,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99001.0,Acadia (Parish),2017
17,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99003.0,Allen (Parish),2017
18,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99007.0,Assumption (Parish),2017
19,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99011.0,Beauregard (Parish),2017
20,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99019.0,Calcasieu (Parish),2017
21,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99023.0,Cameron (Parish),2017
22,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99031.0,De Soto (Parish),2017
23,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99045.0,Iberia (Parish),2017
24,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99053.0,Jefferson Davis (Parish),2017
25,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99055.0,Lafayette (Parish),2017
26,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99057.0,Lafourche (Parish),2017
27,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99069.0,Natchitoches (Parish),2017
28,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99075.0,Plaquemines (Parish),2017
29,4345,No,No,Yes,Yes,LA,2017-10-16 13:00:00,DR,Hurricane,TROPICAL STORM HARVEY,2017-08-28 08:09:00,2017-09-10 23:59:00,NaT,99079.0,Rapides (Parish),2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47574,31,No,Yes,Yes,Yes,AK,1954-11-10 00:00:00,DR,Other,SEVERE HARDSHIP,1954-11-10 00:00:00,1954-11-10 00:00:00,1957-09-01,NaN,NaN,1954
47575,30,No,Yes,Yes,Yes,IN,1954-10-26 00:00:00,DR,Flood,FLOOD,1954-10-26 00:00:00,1954-10-26 00:00:00,1956-03-01,NaN,NaN,1954
47576,28,No,Yes,Yes,Yes,NC,1954-10-17 00:00:00,DR,Hurricane,HURRICANE,1954-10-17 00:00:00,1954-10-17 00:00:00,1959-01-01,NaN,NaN,1954
47577,29,No,Yes,Yes,Yes,SC,1954-10-17 00:00:00,DR,Hurricane,HURRICANE,1954-10-17 00:00:00,1954-10-17 00:00:00,1959-01-01,NaN,NaN,1954
47578,27,No,Yes,Yes,Yes,NM,1954-10-13 00:00:00,DR,Flood,FLOOD,1954-10-13 00:00:00,1954-10-13 00:00:00,1959-12-01,NaN,NaN,1954
47579,26,No,Yes,Yes,Yes,NY,1954-10-07 00:00:00,DR,Hurricane,HURRICANES,1954-10-07 00:00:00,1954-10-07 00:00:00,1956-12-01,NaN,NaN,1954
47580,25,No,Yes,Yes,Yes,CT,1954-09-17 00:00:00,DR,Hurricane,HURRICANES,1954-09-17 00:00:00,1954-09-17 00:00:00,1957-01-01,NaN,NaN,1954
47581,24,No,Yes,Yes,Yes,ME,1954-09-13 00:00:00,DR,Hurricane,HURRICANES,1954-09-13 00:00:00,1954-09-13 00:00:00,1956-12-01,NaN,NaN,1954
47582,22,No,Yes,Yes,Yes,MA,1954-09-02 00:00:00,DR,Hurricane,HURRICANES,1954-09-02 00:00:00,1954-09-02 00:00:00,1956-12-01,NaN,NaN,1954
47583,23,No,Yes,Yes,Yes,RI,1954-09-02 00:00:00,DR,Hurricane,HURRICANES,1954-09-02 00:00:00,1954-09-02 00:00:00,1956-12-01,NaN,NaN,1954
47584,21,No,Yes,Yes,Yes,WV,1954-08-04 00:00:00,DR,Flood,FLOOD,1954-08-04 00:00:00,1954-08-04 00:00:00,1957-05-01,NaN,NaN,1954
47585,20,No,Yes,Yes,Yes,SD,1954-07-31 00:00:00,DR,Flood,FLOOD,1954-07-31 00:00:00,1954-07-31 00:00:00,1956-02-01,NaN,NaN,1954
47586,19,No,Yes,Yes,Yes,NV,1954-07-14 00:00:00,DR,Earthquake,EARTHQUAKE,1954-07-14 00:00:00,1954-07-14 00:00:00,1957-08-01,NaN,NaN,1954
47587,18,No,Yes,Yes,Yes,TX,1954-07-01 00:00:00,DR,Flood,FLOOD,1954-07-01 00:00:00,1954-07-01 00:00:00,1959-07-01,NaN,NaN,1954
47588,17,No,Yes,Yes,Yes,IA,1954-06-23 00:00:00,DR,Flood,FLOOD,1954-06-23 00:00:00,1954-06-23 00:00:00,1956-02-01,NaN,NaN,1954
47589,16,No,Yes,Yes,Yes,GA,1954-03-17 00:00:00,DR,Tornado,TORNADO,1954-03-17 00:00:00,1954-03-17 00:00:00,1956-11-01,NaN,NaN,1954
47590,15,No,Yes,Yes,Yes,CA,1954-02-05 00:00:00,DR,Flood,FLOOD & EROSION,1954-02-05 00:00:00,1954-02-05 00:00:00,1957-09-01,NaN,NaN,1954
47591,14,No,Yes,Yes,Yes,MS,1953-12-06 00:00:00,DR,Tornado,TORNADO,1953-12-06 00:00:00,1953-12-06 00:00:00,1956-06-01,NaN,NaN,1953
47592,13,No,Yes,Yes,Yes,AK,1953-10-30 00:00:00,DR,Other,SEVERE HARDSHIP,1953-10-30 00:00:00,1953-10-30 00:00:00,1957-09-01,NaN,NaN,1953
47593,12,No,Yes,Yes,Yes,FL,1953-10-22 00:00:00,DR,Flood,FLOOD,1953-10-22 00:00:00,1953-10-22 00:00:00,1956-05-01,NaN,NaN,1953
47594,11,No,Yes,Yes,Yes,NH,1953-07-02 00:00:00,DR,Fire,FOREST FIRE,1953-07-02 00:00:00,1953-07-02 00:00:00,1956-02-01,NaN,NaN,1953
47595,9,No,Yes,Yes,Yes,TX,1953-06-19 00:00:00,DR,Flood,FLOOD,1953-06-19 00:00:00,1953-06-19 00:00:00,1958-01-01,NaN,NaN,1953
47596,7,No,Yes,Yes,Yes,MA,1953-06-11 00:00:00,DR,Tornado,TORNADO,1953-06-11 00:00:00,1953-06-11 00:00:00,1956-06-01,NaN,NaN,1953
47597,8,No,Yes,Yes,Yes,IA,1953-06-11 00:00:00,DR,Flood,FLOOD,1953-06-11 00:00:00,1953-06-11 00:00:00,1955-11-01,NaN,NaN,1953
47598,6,No,Yes,Yes,Yes,MI,1953-06-09 00:00:00,DR,Tornado,TORNADO,1953-06-09 00:00:00,1953-06-09 00:00:00,1956-03-30,NaN,NaN,1953
47599,5,No,Yes,Yes,Yes,MT,1953-06-06 00:00:00,DR,Flood,FLOODS,1953-06-06 00:00:00,1953-06-06 00:00:00,1955-12-01,NaN,NaN,1953
47600,4,No,Yes,Yes,Yes,MI,1953-06-02 00:00:00,DR,Tornado,TORNADO,1953-06-02 00:00:00,1953-06-02 00:00:00,1956-02-01,NaN,NaN,1953
47601,3,No,Yes,Yes,Yes,LA,1953-05-29 00:00:00,DR,Flood,FLOOD,1953-05-29 00:00:00,1953-05-29 00:00:00,1960-02-01,NaN,NaN,1953
47602,2,No,Yes,Yes,Yes,TX,1953-05-15 00:00:00,DR,Tornado,TORNADO & HEAVY RAINFALL,1953-05-15 00:00:00,1953-05-15 00:00:00,1958-01-01,NaN,NaN,1953
47603,1,No,Yes,Yes,Yes,GA,1953-05-02 00:00:00,DR,Tornado,TORNADO,1953-05-02 00:00:00,1953-05-02 00:00:00,1954-06-01,NaN,NaN,1953

In [35]:
declartion_year = fema_declarations.groupby(["year"]).count()
declartion_year.reset_index(level=0, inplace=True)
declartion_year

,year,Disaster Number,IH Program Declared,IA Program Declared,PA Program Declared,HM Program Declared,State,Declaration Date,Disaster Type,Incident Type,Title,Incident Begin Date,Incident End Date,Disaster Close Out Date,Place Code,Declared County/Area
0,1953,13,13,13,13,13,13,13,13,13,13,13,13,13,0,0
1,1954,17,17,17,17,17,17,17,17,17,17,17,17,17,0,0
2,1955,18,18,18,18,18,18,18,18,18,18,18,18,18,0,0
3,1956,16,16,16,16,16,16,16,16,16,16,16,16,16,0,0
4,1957,16,16,16,16,16,16,16,16,16,16,16,16,16,0,0
5,1958,7,7,7,7,7,7,7,7,7,7,7,7,7,0,0
6,1959,7,7,7,7,7,7,7,7,7,7,7,7,7,1,1
7,1960,12,12,12,12,12,12,12,12,12,12,12,12,12,0,0
8,1961,12,12,12,12,12,12,12,12,12,12,12,12,12,0,0
9,1962,22,22,22,22,22,22,22,22,22,22,22,22,22,0,0
10,1963,20,20,20,20,20,20,20,20,20,20,20,20,20,0,0
11,1964,136,136,136,136,136,136,136,136,136,136,136,136,136,115,115
12,1965,429,429,429,429,429,429,429,429,429,429,429,429,429,429,429
13,1966,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120
14,1967,197,197,197,197,197,197,197,197,197,197,197,197,197,197,197
15,1968,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162
16,1969,505,505,505,505,505,505,505,505,505,505,505,505,505,505,505
17,1970,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221
18,1971,171,171,171,171,171,171,171,171,171,171,171,171,171,170,170
19,1972,526,526,526,526,526,526,526,526,526,526,526,526,526,526,526
20,1973,863,863,863,863,863,863,863,863,863,863,863,863,863,863,863
21,1974,619,619,619,619,619,619,619,619,619,619,619,619,619,619,619
22,1975,460,460,460,460,460,460,460,460,460,460,460,460,460,460,460
23,1976,586,586,586,586,586,586,586,586,586,586,586,586,586,586,586
24,1977,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160
25,1978,440,440,440,440,440,440,440,440,440,440,440,440,440,440,440
26,1979,476,476,476,476,476,476,476,476,476,476,476,476,476,476,476
27,1980,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200
28,1981,52,52,52,52,52,52,52,52,52,52,52,52,52,51,51
29,1982,158,158,158,158,158,158,158,158,158,158,158,158,158,157,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,1988,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51
36,1989,462,462,462,462,462,462,462,462,462,462,462,462,462,462,462
37,1990,610,610,610,610,610,610,610,610,610,610,610,610,610,610,610
38,1991,623,623,623,623,623,623,623,623,623,623,623,623,623,623,623
39,1992,379,379,379,379,379,379,379,379,379,379,379,379,379,379,379
40,1993,1705,1705,1705,1705,1705,1705,1705,1705,1705,1705,1705,1705,1705,1705,1705
41,1994,676,676,676,676,676,676,676,676,676,676,676,676,676,676,676
42,1995,602,602,602,602,602,602,602,602,602,602,602,602,599,601,601
43,1996,1622,1622,1622,1622,1622,1622,1622,1622,1622,1622,1622,1622,1622,1621,1621
44,1997,919,919,919,919,919,919,919,919,919,919,919,919,919,919,919
45,1998,1497,1497,1497,1497,1497,1497,1497,1497,1497,1497,1497,1497,1404,1492,1492
46,1999,1419,1419,1419,1419,1419,1419,1419,1419,1419,1419,1419,1359,1400,1419,1419
47,2000,1082,1082,1082,1082,1082,1082,1082,1082,1082,1082,1082,1003,1078,1082,1082
48,2001,1148,1148,1148,1148,1148,1148,1148,1148,1148,1148,1148,1102,1055,1147,1147
49,2002,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1038,1040,1039,1039
50,2003,1574,1574,1574,1574,1574,1574,1574,1574,1574,1574,1574,1572,1569,1573,1573
51,2004,1853,1853,1853,1853,1853,1853,1853,1853,1853,1853,1853,1851,1464,1853,1853
52,2005,4736,4736,4736,4736,4736,4736,4736,4736,4736,4736,4736,4728,3879,4736,4736
53,2006,975,975,975,975,975,975,975,975,975,975,975,924,841,975,975
54,2007,1640,1640,1640,1640,1640,1640,1640,1640,1640,1640,1640,1601,1330,1640,1640
55,2008,2300,2300,2300,2300,2300,2300,2300,2300,2300,2300,2300,2283,1465,2300,2300
56,2009,1265,1265,1265,1265,1265,1265,1265,1265,1265,1265,1265,1255,648,1262,1262
57,2010,1635,1635,1635,1635,1635,1635,1635,1635,1635,1635,1635,1632,926,1635,1635
58,2011,2680,2680,2680,2680,2680,2680,2680,2680,2680,2680,2680,2662,963,2680,2680
59,2012,1261,1261,1261,1261,1261,1261,1261,1261,1261,1261,1261,1260,661,1260,1260
60,2013,737,737,737,737,737,737,737,737,737,737,737,737,81,737,737
61,2014,654,654,654,654,654,654,654,654,654,654,654,654,156,654,654
62,2015,916,916,916,916,916,916,916,916,916,916,916,916,0,916,916
63,2016,1132,1132,1132,1132,1132,1132,1132,1132,1132,1132,1132,1132,1,1132,1132
64,2017,1529,1529,1529,1529,1529,1529,1529,1529,1529,1529,1529,1240,0,1529,1529

In [36]:
year_data = declartion_year[["year", "Incident Type"]]
year_data

    year  Incident Type
0   1953             13
1   1954             17
2   1955             18
3   1956             16
4   1957             16
5   1958              7
6   1959              7
7   1960             12
8   1961             12
9   1962             22
10  1963             20
11  1964            136
12  1965            429
13  1966            120
14  1967            197
15  1968            162
16  1969            505
17  1970            221
18  1971            171
19  1972            526
20  1973            863
21  1974            619
22  1975            460
23  1976            586
24  1977           1160
25  1978            440
26  1979            476
27  1980            200
28  1981             52
29  1982            158
..   ...            ...
35  1988             51
36  1989            462
37  1990            610
38  1991            623
39  1992            379
40  1993           1705
41  1994            676
42  1995            602
43  1996           1622
44  1997            919
45  1998           1497
46  1999           1419
47  2000           1082
48  2001           1148
49  2002           1040
50  2003           1574
51  2004           1853
52  2005           4736
53  2006            975
54  2007           1640
55  2008           2300
56  2009           1265
57  2010           1635
58  2011           2680
59  2012           1261
60  2013            737
61  2014            654
62  2015            916
63  2016           1132
64  2017           1529

[65 rows x 2 columns]